export const LOADING = 'LOADING'
export const LOADING_MORE = 'LOADING_MORE'
export const REFRESHING = 'REFRESHING'

export const SAVE_STATION = 'SAVE_STATION'
export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_CONFIGURATION = 'GET_CONFIGURATION'
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const SHOW_PUSH_NOTIFICATION = 'SHOW_PUSH_NOTIFICATION'

export const GET_CURRENT_PROGRAM = 'GET_CURRENT_PROGRAM'
export const SET_RADIO_PLAYING = 'SET_RADIO_PLAYING'
export const GET_UPCOMING_PROGRAMS = 'GET_UPCOMING_PROGRAMS'
export const GET_TRENDING_PROGRAMS = 'GET_TRENDING_PROGRAMS'

export const GET_PREVIOUS_PROGRAMS = 'GET_PREVIOUS_PROGRAMS'
export const FILTER_PROGRAMS = 'FILTER_PROGRAMS'
export const SELECT_PROGRAM = 'SELECT_PROGRAM'
export const GET_PROGRAM_EPISODES = 'GET_PROGRAM_EPISODES'

export const FETCH_ALL_PROGRAMS_IN_DAY = 'FETCH_ALL_PROGRAMS_IN_DAY'

export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_META = 'GET_COMMENTS_META'


export const CREATE_REPORT = 'CREATE_REPORT'
export const GET_REPORTS = 'GET_REPORTS'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const GET_ARTICLES = 'GET_ARTICLES'
export const SELECT_ARTICLE = 'SELECT_ARTICLE'
export const FETCHING_ARTICLES = 'FETCHING_ARTICLES'

export const GET_POLLS = 'GET_POLLS'
export const SELECT_POLL = 'SELECT_POLL'

export const PLAY_PROGRAM = 'PLAY_PROGRAM'

export const FETCH_ADVERT = 'FETCH_ADVERT'
export const ADVERT_LOADING = 'ADVERT_LOADING'
export const ADVERT_ERROR = 'ADVERT_ERROR'
